BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkBook.DataAccess.Repository.IRepository;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _context;
        public CoverTypeController(IUnitOfWork context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var cats = _context.CoverType.GetAll();
            return View(cats);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            
            if (ModelState.IsValid)
            {
                _context.CoverType.Add(obj);
                _context.Save();
                TempData["success"] = "Data Have Been Added";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _context.CoverType.GetFirstOrDefault(n => n.Id == Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
           
            if (ModelState.IsValid)
            {
                _context.CoverType.Update(obj);
                _context.Save();
                TempData["success"] = "Data Have Been Updated";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _context.CoverType.GetFirstOrDefault(n => n.Id == Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(CoverType obj)
        {
            _context.CoverType.Remove(obj);
            _context.Save();
            TempData["success"] = "Data Have Been Deleted";
            return RedirectToAction("Index");

        }
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}



<form method="post" asp-action="Create">
<div class="p-3 mt-4">
<h2 class="text-primary">Create New Cover Type</h2>
    </div>
@*     <div asp-validation-summary="All"></div>
 *@    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
   
    <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
    <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />

    }

}

BulkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}



<form method="post" asp-action="Delete">
<div class="p-3 mt-4">
<h2 class="text-primary">Edit Cover Type</h2>
    </div>
@*     <div asp-validation-summary="All"></div>
 *@    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" disabled class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
   
    <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
    <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />

    }

}

BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}



<form method="post" asp-action="Edit">
<div class="p-3 mt-4">
<h2 class="text-primary">Edit Cover Type</h2>
    </div>
@*     <div asp-validation-summary="All"></div>
 *@    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
    <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />

    }

}

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row p-4">
        <div class="col-6">
            <h2 class="text-primary">Cover Type List</h2>
            
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary"> <i class="bi bi-plus-circle"></i> &nbsp; New</a>
        </div>
    </div>



<table class="table table-bordered table-hover table-striped" style="width:100%" >
    <thead>
        <tr>
            <th scope="col">
                Id
            </th>
            <th scope="col">
                Cover Type Name
            </th>
            <th scope="col">

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="30%" scope="row" >
                    @item.Id
                </td>
                <td width="40%" scope="row">
                    @item.Name
                </td>
                <td width="60%" scope="row">
                   <div class="w-75 btn-group" role="group">
                            <a class="btn btn-info mx-2" asp-controller="CoverType" asp-action="Edit" asp-route-Id="@item.Id" ><i class="bi bi-pencil-square"></i> Edit</a>
                            <a class="btn btn-danger mx-2" asp-controller="CoverType" asp-action="Delete" asp-route-Id="@item.Id"><i class="bi bi-trash"></i> Delete</a>

                   </div>

                </td>
            </tr>
        }
    </tbody>
</table>
</div>